# -------------------------------------------------------
# Application
# -------------------------------------------------------
spring.application.name=distributed-payment-system


# -------------------------------------------------------
# Server
# -------------------------------------------------------
server.port=${SERVER_PORT:8080}
server.shutdown=graceful

# -------------------------------------------------------
# Datasource
# -------------------------------------------------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_authdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:3025}
spring.datasource.driver-class-name=org.postgresql.Driver


# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# -------------------------------------------------------
# JPA / Hibernate
# -------------------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public


# -------------------------------------------------------
# Flyway
# -------------------------------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true


# -------------------------------------------------------
# Actuator
# -------------------------------------------------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized


# -------------------------------------------------------
# Logging
# -------------------------------------------------------
logging.level.com.capstone.payment=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN


# -------------------------------------------------------
# Ledger Mock Service
# -------------------------------------------------------
ledger.base-url=${LEDGER_URL:http://localhost:9090}


# -------------------------------------------------------
# Resilience4j TimeLimiter
# -------------------------------------------------------
resilience4j.timelimiter.instances.ledger.timeout-duration=2s
resilience4j.timelimiter.instances.ledger.cancel-running-future=true

resilience4j.timelimiter.instances.ledgerCompensation.timeout-duration=5s
resilience4j.timelimiter.instances.ledgerCompensation.cancel-running-future=true

# -------------------------------------------------------
# Resilience4j Retry
# -------------------------------------------------------
resilience4j.retry.instances.ledger.max-attempts=3
resilience4j.retry.instances.ledger.wait-duration=200ms
resilience4j.retry.instances.ledger.enable-exponential-backoff=true
resilience4j.retry.instances.ledger.exponential-backoff-multiplier=2
resilience4j.retry.instances.ledger.exponential-max-wait-duration=2s
resilience4j.retry.instances.ledger.randomized-wait-factor=0.5
resilience4j.retry.instances.ledger.retry-exceptions[0]=com.kennycode.distributedpaymentsystem.service.LedgerException
resilience4j.retry.instances.ledger.retry-exceptions[1]=org.springframework.web.client.ResourceAccessException
resilience4j.retry.instances.ledger.ignore-exceptions[0]=com.kennycode.distributedpaymentsystem.exception.CardNotFoundException

resilience4j.retry.instances.ledgerCompensation.max-attempts=5
resilience4j.retry.instances.ledgerCompensation.wait-duration=500ms
resilience4j.retry.instances.ledgerCompensation.enable-exponential-backoff=true
resilience4j.retry.instances.ledgerCompensation.exponential-backoff-multiplier=2
resilience4j.retry.instances.ledgerCompensation.exponential-max-wait-duration=10s
resilience4j.retry.instances.ledgerCompensation.randomized-wait-factor=0.3
resilience4j.retry.instances.ledgerCompensation.retry-exceptions[0]=com.kennycode.distributedpaymentsystem.exception.LedgerException
resilience4j.retry.instances.ledgerCompensation.retry-exceptions[1]=org.springframework.web.client.ResourceAccessException


# -------------------------------------------------------
# Resilience4j Circuit Breaker
# -------------------------------------------------------
resilience4j.circuitbreaker.instances.ledger.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.ledger.sliding-window-size=10
resilience4j.circuitbreaker.instances.ledger.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ledger.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.ledger.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ledger.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.ledger.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.ledger.record-exceptions[0]=com.kennycode.distributedpaymentsystem.exception.LedgerException
resilience4j.circuitbreaker.instances.ledger.record-exceptions[1]=org.springframework.web.cli




